################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.c \
../Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.o \
./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.d \
./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/DSP/Source/FilteringFunctions/%.o Drivers/DSP/Source/FilteringFunctions/%.su Drivers/DSP/Source/FilteringFunctions/%.cyclo: ../Drivers/DSP/Source/FilteringFunctions/%.c Drivers/DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -IC:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/STM32L0xx_HAL_Driver/Inc -IC:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -IC:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include -IC:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-DSP-2f-Source-2f-FilteringFunctions

clean-Drivers-2f-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.cyclo ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.d ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.o ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctions.su ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.d ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.o ./Drivers/DSP/Source/FilteringFunctions/FilteringFunctionsF16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_conv_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f16.su
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_f64.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_correlate_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_f64.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.d
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_f64.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Drivers/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q15.su
	-$(RM) ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q15.su ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.d ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.o ./Drivers/DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Drivers-2f-DSP-2f-Source-2f-FilteringFunctions

