################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/CMSIS/DSP/Source/FilteringFunctions/%.o Drivers/CMSIS/DSP/Source/FilteringFunctions/%.su Drivers/CMSIS/DSP/Source/FilteringFunctions/%.cyclo: ../Drivers/CMSIS/DSP/Source/FilteringFunctions/%.c Drivers/CMSIS/DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I"C:/Users/joris/Documents/1. Projects/Stage/4. STM32/MJSGadget/Lib" -I"C:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/CMSIS/Include" -I"C:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/STM32L0xx_HAL_Driver/Inc/Legacy" -I"C:/Users/joris/STM32Cube/Repository/STM32Cube_FW_L0_V1.12.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/CMSIS/Include -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I"../Drivers/CMSIS/Device/ST/STM32L0xx" -I../Drivers/CMSIS/DSP -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.su
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o
	-$(RM) ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.su ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o ./Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

